# docker-compose.yml
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      # Add other environment variables as needed
      # - REACT_APP_API_URL=http://api.example.com
    networks:
      - react-network

  # Uncomment if you need a backend service
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - react-network

networks:
  react-network:
    driver: bridge